import type { CommandDefinition } from "$lib/features/search/types/command_palette";

export const COMMANDS_REGISTRY: CommandDefinition[] = [
  {
    id: "create_new_note",
    label: "Create new note",
    description: "Create an untitled note in the current folder",
    keywords: ["new", "add", "create", "note", "file", "document"],
    icon: "file-plus",
  },
  {
    id: "create_new_canvas",
    label: "New Canvas",
    description: "Create a new JSON Canvas board",
    keywords: ["new", "canvas", "board", "spatial", "create"],
    icon: "file-plus",
  },
  {
    id: "create_new_drawing",
    label: "New Drawing",
    description: "Create a new Excalidraw drawing",
    keywords: [
      "new",
      "drawing",
      "excalidraw",
      "sketch",
      "create",
      "whiteboard",
    ],
    icon: "file-plus",
  },
  {
    id: "change_vault",
    label: "Change vault",
    description: "Switch to a different vault",
    keywords: ["switch", "vault", "folder", "workspace", "change", "open"],
    icon: "folder-open",
  },
  {
    id: "open_settings",
    label: "Settings",
    description: "Open application settings",
    keywords: ["settings", "preferences", "config", "options", "configure"],
    icon: "settings",
  },
  {
    id: "open_hotkeys",
    label: "Keyboard Shortcuts",
    description: "Configure keyboard shortcuts and hotkeys",
    keywords: [
      "hotkeys",
      "keyboard",
      "shortcuts",
      "keybindings",
      "keys",
      "remap",
      "bindings",
    ],
    icon: "keyboard",
  },
  {
    id: "sync_index",
    label: "Sync index",
    description: "Rescan vault files and sync search index",
    keywords: ["index", "sync", "search", "vault", "refresh", "rescan"],
    icon: "refresh-cw",
  },
  {
    id: "reindex_vault",
    label: "Reindex vault",
    description: "Rebuild search index for the current vault",
    keywords: ["index", "rebuild", "search", "vault", "reindex", "repair"],
    icon: "settings",
  },
  {
    id: "show_vault_dashboard",
    label: "Show vault dashboard",
    description: "Open vault dashboard overview",
    keywords: ["dashboard", "vault", "overview", "stats", "activity"],
    icon: "folder-open",
  },
  {
    id: "git_version_history",
    label: "Version History",
    description: "View version history for the current note",
    keywords: ["history", "versions", "git", "log", "timeline"],
    icon: "history",
  },
  {
    id: "git_create_checkpoint",
    label: "Create Checkpoint",
    description: "Save a named checkpoint of the current state",
    keywords: ["checkpoint", "snapshot", "save", "git", "commit"],
    icon: "bookmark",
  },
  {
    id: "git_init_repo",
    label: "Initialize Git Repository",
    description: "Initialize version control for this vault",
    keywords: ["git", "init", "repo", "repository", "version", "control"],
    icon: "git-branch",
  },
  {
    id: "git_push",
    label: "Git Push",
    description: "Push local commits to the configured upstream remote",
    keywords: ["git", "push", "remote", "upstream", "publish", "sync"],
    icon: "git-branch",
  },
  {
    id: "git_pull",
    label: "Git Pull",
    description: "Fetch and merge remote changes into the current branch",
    keywords: ["git", "pull", "remote", "merge", "upstream", "sync"],
    icon: "git-branch",
  },
  {
    id: "git_fetch",
    label: "Git Fetch",
    description: "Refresh remote status without merging local changes",
    keywords: ["git", "fetch", "remote", "ahead", "behind", "refresh"],
    icon: "refresh-cw",
  },
  {
    id: "git_add_remote",
    label: "Add Git Remote",
    description: "Configure the origin remote for this vault",
    keywords: ["git", "remote", "origin", "repository", "url", "connect"],
    icon: "link",
  },
  {
    id: "ai_assistant",
    label: "AI Assistant",
    description: "Open the AI assistant for the current note",
    keywords: [
      "ai",
      "assistant",
      "edit",
      "rewrite",
      "llm",
      "claude",
      "codex",
      "ollama",
      "local",
    ],
    icon: "sparkles",
  },
  {
    id: "toggle_links_panel",
    label: "Toggle Links Panel",
    description: "Show or hide backlinks and outlinks panel",
    keywords: ["links", "backlinks", "outlinks", "context", "panel", "sidebar"],
    icon: "link",
  },
  {
    id: "toggle_graph_panel",
    label: "Toggle Graph Panel",
    description: "Show or hide the note neighborhood graph",
    keywords: ["graph", "links", "context", "panel", "neighborhood", "visual"],
    icon: "link",
  },
  {
    id: "toggle_outline_panel",
    label: "Toggle Outline Panel",
    description: "Show or hide the document heading outline",
    keywords: [
      "outline",
      "headings",
      "toc",
      "table of contents",
      "navigation",
      "structure",
    ],
    icon: "list-tree",
  },
  {
    id: "toggle_tasks_panel",
    label: "Toggle Tasks Panel",
    description: "Show or hide the tasks, Kanban, and schedule panel",
    keywords: ["tasks", "todo", "done", "kanban", "schedule", "calendar"],
    icon: "refresh-cw",
  },
  {
    id: "quick_capture_task",
    label: "Quick Capture Task",
    description: "Rapidly add a new task to your vault",
    keywords: ["tasks", "todo", "new", "add", "capture", "quick"],
    icon: "file-plus",
  },
  {
    id: "show_tasks_list",
    label: "Show Task List",
    description: "Switch tasks panel to list view",
    keywords: ["tasks", "todo", "list", "view"],
    icon: "list-tree",
  },
  {
    id: "show_tasks_kanban",
    label: "Show Task Kanban",
    description: "Switch tasks panel to Kanban board view",
    keywords: ["tasks", "todo", "kanban", "board", "view"],
    icon: "settings",
  },
  {
    id: "show_tasks_schedule",
    label: "Show Task Schedule",
    description: "Switch tasks panel to schedule/calendar view",
    keywords: ["tasks", "todo", "schedule", "calendar", "view", "due"],
    icon: "refresh-cw",
  },
  {
    id: "check_for_updates",
    label: "Check for Updates",
    description: "Check if a new version of Badgerly is available",
    keywords: ["update", "upgrade", "version", "release", "new version"],
    icon: "refresh-cw",
  },
  {
    id: "export_as_pdf",
    label: "Export as PDF",
    description: "Export the current note as a PDF file",
    keywords: ["export", "pdf", "save", "print", "download"],
    icon: "file-down",
  },
  {
    id: "terminal_toggle",
    label: "Toggle Terminal",
    description: "Show or hide the terminal panel",
    keywords: [
      "terminal",
      "shell",
      "console",
      "command",
      "line",
      "pty",
      "toggle",
    ],
    icon: "terminal",
  },
  {
    id: "terminal_new_session",
    label: "New Terminal Session",
    description: "Open a new terminal session in a new tab",
    keywords: ["terminal", "shell", "console", "new", "tab", "session", "add"],
    icon: "terminal",
  },
  {
    id: "open_plugins",
    label: "Plugins",
    description: "Manage installed plugins",
    keywords: ["plugins", "extensions", "addons", "manage", "install"],
    icon: "blocks",
  },
];
