import type { EditorSettings } from "$lib/shared/types/editor_settings";

export type SettingDefinition = {
  key: keyof EditorSettings;
  label: string;
  description: string;
  category: string;
  keywords: string[];
};

export const SETTINGS_REGISTRY: SettingDefinition[] = [
  {
    key: "attachment_folder",
    label: "Attachment Folder",
    description: "Folder name for storing pasted images and attachments",
    category: "Files",
    keywords: [
      "assets",
      "images",
      "attachments",
      "folder",
      "path",
      "upload",
      "paste",
    ],
  },
  {
    key: "show_hidden_files",
    label: "Show Hidden Files",
    description: "Show dot-prefixed files and folders in the file tree",
    category: "Files",
    keywords: [
      "hidden",
      "dot",
      "dotfiles",
      "dotfolders",
      "invisible",
      "show",
      "hide",
    ],
  },
  {
    key: "autosave_enabled",
    label: "Autosave",
    description: "Automatically save markdown notes after edits",
    category: "Files",
    keywords: [
      "autosave",
      "auto save",
      "save",
      "automatic",
      "draft",
      "unsaved",
    ],
  },
  {
    key: "git_autocommit_mode",
    label: "Auto-commit Mode",
    description: "When to automatically commit saved changes to Git",
    category: "Git",
    keywords: [
      "git",
      "autocommit",
      "auto commit",
      "commit",
      "version",
      "automatic",
      "mode",
    ],
  },
  {
    key: "git_autocommit_interval_minutes",
    label: "Auto-commit Interval",
    description: "Minutes between automatic commits (when using interval mode)",
    category: "Git",
    keywords: [
      "git",
      "autocommit",
      "interval",
      "minutes",
      "timer",
      "frequency",
    ],
  },
  {
    key: "git_pull_strategy",
    label: "Pull Strategy",
    description:
      "How Git pull integrates remote changes into the current branch",
    category: "Git",
    keywords: ["git", "pull", "merge", "rebase", "ff-only", "strategy"],
  },
  {
    key: "git_auto_fetch_interval_minutes",
    label: "Auto-fetch Interval",
    description: "How often to refresh remote status in the background",
    category: "Git",
    keywords: [
      "git",
      "fetch",
      "remote",
      "interval",
      "minutes",
      "background",
      "poll",
    ],
  },
  {
    key: "show_vault_dashboard_on_open",
    label: "Show Vault Dashboard on Open",
    description: "Open vault dashboard automatically when switching vaults",
    category: "Misc",
    keywords: ["vault", "dashboard", "overview", "open", "startup", "switch"],
  },
  {
    key: "max_open_tabs",
    label: "Max Open Tabs",
    description: "Maximum number of tabs that can be open at once",
    category: "Layout",
    keywords: ["tabs", "limit", "max", "open", "performance", "editor"],
  },
  {
    key: "editor_max_width_ch",
    label: "Editor Max Width",
    description: "Maximum line width for the editor content in characters",
    category: "Layout",
    keywords: ["editor", "width", "line length", "layout", "readability"],
  },
  {
    key: "terminal_shell_path",
    label: "Shell Path",
    description: "Path to the shell executable used by the terminal",
    category: "Terminal",
    keywords: ["terminal", "shell", "zsh", "bash", "path", "command", "pty"],
  },
  {
    key: "terminal_font_size_px",
    label: "Terminal Font Size",
    description: "Font size used by the embedded terminal",
    category: "Terminal",
    keywords: ["terminal", "font", "size", "text", "xterm"],
  },
  {
    key: "terminal_scrollback",
    label: "Terminal Scrollback",
    description: "Maximum number of lines kept in terminal history",
    category: "Terminal",
    keywords: ["terminal", "scrollback", "history", "lines", "buffer"],
  },
  {
    key: "terminal_cursor_blink",
    label: "Terminal Cursor Blink",
    description: "Animate the terminal cursor while focused",
    category: "Terminal",
    keywords: ["terminal", "cursor", "blink", "caret"],
  },
  {
    key: "terminal_follow_active_vault",
    label: "Follow Active Vault",
    description:
      "Respawn the terminal in the active vault when switching vaults",
    category: "Terminal",
    keywords: ["terminal", "vault", "cwd", "working directory", "follow"],
  },
  {
    key: "ai_ollama_model",
    label: "Ollama Model",
    description: "Default Ollama model used for AI edits",
    category: "AI",
    keywords: ["ai", "ollama", "model", "llm", "local"],
  },
  {
    key: "ai_claude_command",
    label: "Claude Command",
    description: "CLI command or executable path for Claude Code",
    category: "AI",
    keywords: ["ai", "claude", "command", "path", "cli"],
  },
  {
    key: "ai_codex_command",
    label: "Codex Command",
    description: "CLI command or executable path for Codex",
    category: "AI",
    keywords: ["ai", "codex", "command", "path", "cli"],
  },
  {
    key: "ai_ollama_command",
    label: "Ollama Command",
    description: "CLI command or executable path for Ollama",
    category: "AI",
    keywords: ["ai", "ollama", "command", "path", "cli"],
  },
  {
    key: "ai_execution_timeout_seconds",
    label: "AI Timeout",
    description: "Maximum time to wait for an AI CLI response",
    category: "AI",
    keywords: ["ai", "timeout", "seconds", "duration", "cli"],
  },
  {
    key: "document_pdf_default_zoom",
    label: "PDF Default Zoom",
    description: "Initial zoom mode when opening PDFs",
    category: "Documents",
    keywords: ["pdf", "zoom", "fit width", "documents", "viewer"],
  },
  {
    key: "document_code_wrap",
    label: "Wrap Code/Text Documents",
    description: "Wrap long lines in code and plain-text viewers",
    category: "Documents",
    keywords: ["documents", "viewer", "code", "text", "wrap", "line wrap"],
  },
  {
    key: "document_image_background",
    label: "Image Background",
    description: "Background style behind images in the document viewer",
    category: "Documents",
    keywords: ["documents", "image", "background", "checkerboard", "viewer"],
  },
  {
    key: "document_inactive_cache_limit",
    label: "Inactive Document Cache",
    description: "How many inactive document payloads stay cached",
    category: "Documents",
    keywords: ["documents", "cache", "inactive", "performance", "memory"],
  },
];
