import type { EditorSettings } from "$lib/shared/types/editor_settings";

export type SettingDefinition = {
  key: keyof EditorSettings;
  label: string;
  description: string;
  category: string;
  keywords: string[];
};

export const SETTINGS_REGISTRY: SettingDefinition[] = [
  {
    key: "default_note_name_template",
    label: "Default Note Name",
    description:
      "Template for new note names using strftime tokens: %Y (year), %m (month), %d (day), %H (hour), %M (minute), %S (second). Leave empty for Untitled-N.",
    category: "Files",
    keywords: [
      "name",
      "template",
      "date",
      "daily",
      "zettelkasten",
      "strftime",
      "default",
      "naming",
    ],
  },
  {
    key: "attachment_folder",
    label: "Attachment Folder",
    description: "Folder name for storing pasted images and attachments",
    category: "Files",
    keywords: [
      "assets",
      "images",
      "attachments",
      "folder",
      "path",
      "upload",
      "paste",
    ],
  },
  {
    key: "ignored_folders",
    label: "Ignored Folders",
    description:
      "Vault-relative folders to exclude from the tree and indexing, in addition to .vaultignore and .gitignore",
    category: "Files",
    keywords: [
      "ignore",
      "ignored",
      "vaultignore",
      "gitignore",
      "folder",
      "exclude",
      "skip",
    ],
  },
  {
    key: "show_hidden_files",
    label: "Show Hidden Files",
    description: "Show dot-prefixed files and folders in the file tree",
    category: "Files",
    keywords: [
      "hidden",
      "dot",
      "dotfiles",
      "dotfolders",
      "invisible",
      "show",
      "hide",
    ],
  },
  {
    key: "autosave_enabled",
    label: "Autosave",
    description: "Automatically save markdown notes after edits",
    category: "Files",
    keywords: [
      "autosave",
      "auto save",
      "save",
      "automatic",
      "draft",
      "unsaved",
    ],
  },
  {
    key: "autosave_delay_ms",
    label: "Autosave Delay",
    description:
      "Delay in milliseconds before automatically saving after edits",
    category: "Files",
    keywords: [
      "autosave",
      "delay",
      "time",
      "save",
      "automatic",
      "performance",
      "interval",
    ],
  },
  {
    key: "git_autocommit_mode",
    label: "Auto-commit Mode",
    description: "When to automatically commit saved changes to Git",
    category: "Git",
    keywords: [
      "git",
      "autocommit",
      "auto commit",
      "commit",
      "version",
      "automatic",
      "mode",
    ],
  },
  {
    key: "git_autocommit_interval_minutes",
    label: "Auto-commit Interval",
    description: "Minutes between automatic commits (when using interval mode)",
    category: "Git",
    keywords: [
      "git",
      "autocommit",
      "interval",
      "minutes",
      "timer",
      "frequency",
    ],
  },
  {
    key: "git_pull_strategy",
    label: "Pull Strategy",
    description:
      "How Git pull integrates remote changes into the current branch",
    category: "Git",
    keywords: ["git", "pull", "merge", "rebase", "ff-only", "strategy"],
  },
  {
    key: "git_auto_fetch_interval_minutes",
    label: "Auto-fetch Interval",
    description: "How often to refresh remote status in the background",
    category: "Git",
    keywords: [
      "git",
      "fetch",
      "remote",
      "interval",
      "minutes",
      "background",
      "poll",
    ],
  },
  {
    key: "show_vault_dashboard_on_open",
    label: "Show Vault Dashboard on Open",
    description: "Open vault dashboard automatically when switching vaults",
    category: "Misc",
    keywords: ["vault", "dashboard", "overview", "open", "startup", "switch"],
  },
  {
    key: "max_open_tabs",
    label: "Max Open Tabs",
    description: "Maximum number of tabs that can be open at once",
    category: "Layout",
    keywords: ["tabs", "limit", "max", "open", "performance", "editor"],
  },
  {
    key: "editor_max_width_ch",
    label: "Editor Max Width",
    description: "Maximum line width for the editor content in characters",
    category: "Layout",
    keywords: ["editor", "width", "line length", "layout", "readability"],
  },
  {
    key: "editor_selection_color",
    label: "Selection Color",
    description: "Override the editor selection highlight color",
    category: "Layout",
    keywords: ["editor", "selection", "highlight", "color", "appearance"],
  },
  {
    key: "editor_heading_spacing_density",
    label: "Heading Spacing",
    description: "Controls vertical spacing around headings in the editor",
    category: "Layout",
    keywords: ["editor", "heading", "spacing", "density", "readability"],
  },
  {
    key: "editor_paragraph_spacing_density",
    label: "Paragraph Spacing",
    description: "Controls paragraph spacing density in the editor",
    category: "Layout",
    keywords: ["editor", "paragraph", "spacing", "density", "readability"],
  },
  {
    key: "editor_list_spacing_density",
    label: "List Spacing",
    description: "Controls list spacing density in the editor",
    category: "Layout",
    keywords: ["editor", "list", "spacing", "density", "readability"],
  },
  {
    key: "editor_code_block_padding",
    label: "Code Block Padding",
    description: "Controls padding inside editor code blocks",
    category: "Layout",
    keywords: ["editor", "code", "block", "padding", "appearance"],
  },
  {
    key: "editor_code_block_radius",
    label: "Code Block Radius",
    description: "Controls corner radius for editor code blocks",
    category: "Layout",
    keywords: ["editor", "code", "block", "radius", "appearance"],
  },
  {
    key: "editor_blockquote_padding",
    label: "Blockquote Padding",
    description: "Controls padding inside editor blockquotes",
    category: "Layout",
    keywords: ["editor", "blockquote", "quote", "padding", "appearance"],
  },
  {
    key: "editor_blockquote_border_width",
    label: "Blockquote Border Width",
    description: "Controls the border width used for editor blockquotes",
    category: "Layout",
    keywords: ["editor", "blockquote", "quote", "border", "width"],
  },
  {
    key: "editor_link_underline_style",
    label: "Link Underline Style",
    description: "Controls how links are underlined in the editor",
    category: "Layout",
    keywords: ["editor", "link", "underline", "style", "appearance"],
  },
  {
    key: "editor_divider_style",
    label: "Divider Style",
    description: "Controls how horizontal rules are displayed in the editor",
    category: "Layout",
    keywords: [
      "editor",
      "divider",
      "horizontal",
      "rule",
      "hr",
      "separator",
      "line",
      "style",
    ],
  },
  {
    key: "terminal_shell_path",
    label: "Shell Path",
    description: "Path to the shell executable used by the terminal",
    category: "Terminal",
    keywords: ["terminal", "shell", "zsh", "bash", "path", "command", "pty"],
  },
  {
    key: "terminal_font_size_px",
    label: "Terminal Font Size",
    description: "Font size used by the embedded terminal",
    category: "Terminal",
    keywords: ["terminal", "font", "size", "text", "xterm"],
  },
  {
    key: "terminal_cursor_blink",
    label: "Terminal Cursor Blink",
    description: "Animate the terminal cursor while focused",
    category: "Terminal",
    keywords: ["terminal", "cursor", "blink", "caret"],
  },
  {
    key: "terminal_follow_active_vault",
    label: "Follow Active Vault",
    description:
      "Respawn the terminal in the active vault when switching vaults",
    category: "Terminal",
    keywords: ["terminal", "vault", "cwd", "working directory", "follow"],
  },
  {
    key: "ai_enabled",
    label: "Enable AI",
    description: "Show AI tools and allow local AI assistant execution",
    category: "AI",
    keywords: ["ai", "assistant", "enable", "disable", "llm", "toggle"],
  },
  {
    key: "ai_providers",
    label: "AI Providers",
    description: "Configured AI CLI providers and their commands",
    category: "AI",
    keywords: [
      "ai",
      "provider",
      "backend",
      "cli",
      "command",
      "ollama",
      "claude",
      "codex",
      "lms",
    ],
  },
  {
    key: "ai_default_provider_id",
    label: "Default Provider",
    description:
      "Provider used when opening AI assistant. Auto picks the first available CLI.",
    category: "AI",
    keywords: ["ai", "assistant", "backend", "provider", "default", "auto"],
  },
  {
    key: "ai_execution_timeout_seconds",
    label: "AI Timeout",
    description: "Maximum time to wait for an AI CLI response",
    category: "AI",
    keywords: ["ai", "timeout", "seconds", "duration", "cli"],
  },
  {
    key: "document_pdf_default_zoom",
    label: "PDF Default Zoom",
    description: "Initial zoom mode when opening PDFs",
    category: "Documents",
    keywords: ["pdf", "zoom", "fit width", "documents", "viewer"],
  },
  {
    key: "document_code_wrap",
    label: "Wrap Code/Text Documents",
    description: "Wrap long lines in code and plain-text viewers",
    category: "Documents",
    keywords: ["documents", "viewer", "code", "text", "wrap", "line wrap"],
  },
  {
    key: "document_image_background",
    label: "Image Background",
    description: "Background style behind images in the document viewer",
    category: "Documents",
    keywords: ["documents", "image", "background", "checkerboard", "viewer"],
  },
  {
    key: "document_inactive_cache_limit",
    label: "Inactive Document Cache",
    description: "How many inactive document payloads stay cached",
    category: "Documents",
    keywords: ["documents", "cache", "inactive", "performance", "memory"],
  },
  {
    key: "semantic_similarity_threshold",
    label: "Similarity Threshold",
    description:
      "Minimum similarity (0–1) for suggested links and graph edges. Lower values show more connections.",
    category: "Semantic",
    keywords: ["semantic", "similarity", "threshold", "distance", "embedding"],
  },
  {
    key: "semantic_suggested_links_limit",
    label: "Suggested Links Limit",
    description:
      "Maximum number of suggested wiki-links shown in the links panel",
    category: "Semantic",
    keywords: ["suggested", "links", "limit", "prediction"],
  },
  {
    key: "semantic_graph_edges_per_note",
    label: "Graph Edges per Note",
    description:
      "How many semantic neighbors to find per note when computing graph edges",
    category: "Semantic",
    keywords: ["graph", "edges", "knn", "neighbors", "semantic"],
  },
  {
    key: "semantic_graph_max_vault_size",
    label: "Graph Max Vault Size",
    description:
      "Semantic graph edges are disabled for vaults larger than this (performance)",
    category: "Semantic",
    keywords: ["graph", "vault", "size", "limit", "performance"],
  },
  {
    key: "semantic_omnibar_fallback_enabled",
    label: "Omnibar Semantic Fallback",
    description:
      "Fall back to semantic search when keyword search returns few results",
    category: "Semantic",
    keywords: ["omnibar", "fallback", "hybrid", "search", "semantic"],
  },
  {
    key: "semantic_omnibar_min_words",
    label: "Omnibar Min Words",
    description: "Minimum query word count to trigger semantic fallback",
    category: "Semantic",
    keywords: ["omnibar", "words", "minimum", "fallback", "threshold"],
  },
  {
    key: "graph_force_link_distance",
    label: "Link Distance",
    description:
      "Target distance between connected nodes (higher = more spread)",
    category: "Graph",
    keywords: ["graph", "force", "layout", "spacing", "link", "distance"],
  },
  {
    key: "graph_force_charge_strength",
    label: "Repulsion Strength",
    description:
      "How strongly nodes push apart (more negative = more repulsion)",
    category: "Graph",
    keywords: ["graph", "force", "layout", "spacing", "charge", "repulsion"],
  },
  {
    key: "graph_force_collision_radius",
    label: "Collision Radius",
    description: "Minimum distance between node centers",
    category: "Graph",
    keywords: ["graph", "force", "layout", "spacing", "collision", "radius"],
  },
  {
    key: "graph_force_charge_max_distance",
    label: "Repulsion Range",
    description: "Maximum distance for repulsion force to act",
    category: "Graph",
    keywords: [
      "graph",
      "force",
      "layout",
      "spacing",
      "charge",
      "range",
      "distance",
    ],
  },
];
